### ISSUE TITLE
AccessViolationException was unhandled by user code

### ISSUE THREAD

**Issue by thangdc** [thangdc/web-automation#10]
The sleep function is work well, but sometime the network connection to slow and it make the script won't working correctly, so I tried to wait until the element has already exists and run to next function, however it make an issue "Attempted to read or write protected memory. This is often an indication that other memory is corrupt.".

I will try another web browser such as cefsharp instead of geckofx, I hope all function can be reuse for new web browser.

**Comment by DreamOnTheGo** [comment]
I meet this problem too,and I also try to wait until the element has already exists and run to next function,I use the timer to check the element,however it makes the application slowly,so i give up.I user the windows.foms.webbrowser to implement the function as you implement.However the IE has many unknown problems,such as the server not suport or the flash not suport or not suport multi thread .see your project on github,I am so happy,i want to discuss with you ,can you give some immediately contact?Such as QQ or MSN?

**Comment by thangdc** [comment]
Hi @DreamOnTheGo, I tried to fix this issue by using latest version of Geckofx and it's working correctly now.
