### ISSUE TITLE
where is the update?

### ISSUE THREAD

**Issue by DreamOnTheGo** [thangdc/web-automation#11]
i see  theg update ->Update change the way to write excel and wait until found element
but  when  i download the  code ,i did not see any change?

**Comment by thangdc** [comment]
Hi,

1. Write excel was changed in Main.cs line 3566 to 3602, the previous code will override the current one each time you call the writeCellExcel function.
2. Another function GetCompleteElementByXPath line 3483 have the code to check the element available before execute the function.
