### ISSUE TITLE
GetElementByXpath not 100% correct 

### ISSUE THREAD

**Issue by syrakozz** [thangdc/web-automation#13]
per example if you tested on google search engine it will always return the first input submit button

**Comment by thangdc** [comment]
Hi @syrakozz,

I have just checked your issue, however it still working from my side, please see my script below:

`go('http://google.com');
var searchbtn = extract("/html[1]/body[1]/center[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/span[1]/span[1]/input[1]", "value");
alert(searchbtn);
var viewfirstbtn = extract("/html[1]/body[1]/center[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/span[2]/span[1]/input[1]", "value");
alert(viewfirstbtn);
var textboxhtml = extract("/html[1]/body[1]/center[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/div[1]/input[1]", "html");
alert(textboxhtml);
`

This script can get the textbox of google engine and 2 buttons.
