### ISSUE TITLE
can't edit your GUI , after change in GUI app crash

### ISSUE THREAD

**Issue by TarrahArshad** [thangdc/web-automation#16]
can't edit your GUI , after change in GUI app crash

**Comment by thangdc** [comment]
Please copy "SciLexer.dll" to this folder "C:\Windows\SysWOW64", some issues related to Scintilla.NET make this issue happen.

**Comment by TarrahArshad** [comment]
i do but problem constantly and again i see another problem in xpath nothing value in extract in  GetElementByXpath() and this line 
                System.Text.RegularExpressions.Match mat = System.Text.RegularExpressions.Regex.Match(tag, "(?<tag>.+)\\[@id='(?<id>.+)'\\]");

everytime is false

**Comment by thangdc** [comment]
I'm not sure about your issue related with GUI, maybe you can copy SciLexer64.dll.
Second thing is the GetElementByXpath() was replaced with GetElement().

Please try again and let me know your result.
