### ISSUE TITLE
launch from webbrowser ,and then automate it

### ISSUE THREAD

**Issue by ellLazar** [thangdc/web-automation#5]
is it possible to launch web browser(IE or chrome) , first
and then take control on this web browser from C# app?
so I can run web client , using IIS  ?

**Comment by thangdc** [comment]
Hi ellLazar,

You can use Selenium to control IE, Chrome even Firefox using C#.
Please see more detail here: http://www.seleniumhq.org/

Sorry for late response.

**Comment by ellLazar** [comment]
is it possible to launch selenium from web browser from any client , without any intsall ?

**Comment by thangdc** [comment]
yes, selenium has the web driver dll, so you can use it without any installation.
Please let me know if anything else.

**Comment by ellLazar** [comment]
selenium

1. if I understand, selenium is an .exe application (?)
  what is the url in web browser  (any client) so I can use to launch
 selenium ?
2. selenium app has to be in web server path, so my url can launch it, please note, I can browse to any html,
but not to an .exe without any warranty 
can you show (one line of code) how I launch the selenium by url ?
what selenium app I put in the web server path ?
or point to some link explanation

**Comment by thangdc** [comment]
Hi ellLazar,

I'm sorry but I don't have much experience with selenium, but I can answer your question with information I have from selenium.

1. Yes the selenium has an .exe file to open the proxy from your application and your browser so you can control it via this proxy.
2. I'm not sure I'm understand you correctly, but that mean you want to open the selenium when the user click on the link to exe file? Currently I don't know how to work with that too, but you can try this link (https://www.google.com/search?q=open+exe+from+browser&ie=utf-8&oe=utf-8)

Thanks
